## Travis CI Integration
language: csharp
solution: libgame.sln

matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
    - os: linux
      dist: trusty
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - os: osx
      osx_image: xcode8
      mono: latest
    - os: osx
      osx_image: xcode8
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1

install:
    - nuget restore libgame.sln
    - nuget install NUnit.Runners -OutputDirectory testrunner

script:
    - xbuild mono-addins/Mono.Addins/Mono.Addins.csproj
    - xbuild libgame.sln
    - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe libgame.UnitTests/bin/Debug/libgame.UnitTests.dll
