## Travis CI Integration
language: csharp
solution: yarhl.sln

matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
    - os: osx
      osx_image: xcode8
      mono: latest

install:
    - nuget restore yarhl.sln
    - nuget install NUnit.Runners -OutputDirectory testrunner

script:
    - msbuild mono-addins/Mono.Addins/Mono.Addins.csproj
    - msbuild yarhl.sln
    - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe yarhl.UnitTests/bin/Debug/yarhl.UnitTests.dll
