## Travis CI Integration
language: csharp
solution: libgame.sln

matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
    - os: osx
      osx_image: xcode8
      mono: latest

install:
    - nuget restore libgame.sln
    - nuget install NUnit.Runners -OutputDirectory testrunner

script:
    - xbuild mono-addins/Mono.Addins/Mono.Addins.csproj
    - xbuild libgame.sln
    - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe libgame.UnitTests/bin/Debug/libgame.UnitTests.dll
