# Yarhl Build and Release pipeline
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: ./build.sh --target=Build --verbosity=diagnostic
  displayName: Build libraries

- script: ./build.sh --target=Run-Unit-Tests --verbosity=diagnostic --exclusive
  displayName: Run unit tests

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'TestResult.xml'
    testRunTitle: Yarhl Tests

- script: ./build.sh --target=Run-AltCover --verbosity=diagnostic --exclusive
  displayName: Analyze code coverage

- script: ./build.sh --target=Run-Linter-Gendarme --verbosity=diagnostic --exclusive
  displayName: Analyze code quality with Gendarme

- script: ./build.sh --target=Build-Doc --verbosity=diagnostic --exclusive
  displayName: Build documentation
