# Yarhl Build and Release pipeline
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: ./build.sh --target=Build --verbosity=diagnostic
  displayName: Build libraries

- script: ./build.sh --target=Run-Unit-Tests --verbosity=diagnostic
  displayName: Run unit tests
